### ISSUE TITLE
SRS Document Uploaded.

### ISSUE THREAD

**Issue by deemaalomair1** [deemaalomair1/CAS741_project#3] opened 2019-10-06 02:11 UTC
Hello Dr.Smith,

I have uploaded SRS document(pdf+tex).
I tried my best to explain chemical reaction balancing in the report. I hope its good enough.  

https://github.com/deemaalomair1/CAS741_project/tree/master/SRS

**Comment by smiths** [comment] 2019-10-06 15:19
@deemaalomair1, thank you for completing this work before the deadline.  I had a quick glance at your work and I noticed two things:

1. Your tex file will not compile for someone else, because you haven't included the required files.  You should reproduce the full structure of the blank project template.  That is there to make your life easier.  :smile:.  You will also need to include any files that you have created.  I may add comments directly to your tex file, and I'll need to be able to compile the document to do so.

2. I don't see a definition for elementT in your data types section.

**Comment by deemaalomair1** [comment] 2019-10-07 16:22
Hello Dr.Smith 
I have added all needed documents and pictures. I tried to compile it now and it's work for me.
also, I added a type definition for ElementT. ( I am not sure if i wrote it right).

this is the new link : 
https://github.com/deemaalomair1/CAS741_project/tree/master/Doc

Best regards,

**Comment by smiths** [comment] 2019-10-07 18:24
I had to make two changes so that I could compile your documentation.  I've pushed the new version to your repo in 3753a46.

You did not copy all of the files from the blank template, so you have missed some helpful material.  In particular, you do not have a .gitignore file.  I suggest that you create one, or simply copy the .gitignore file from blank project template.  That will help prevent you from putting generated files under source control.

You can find the .gitignore file at:

https://gitlab.cas.mcmaster.ca/smiths/cas741/blob/master/BlankProjectTemplate/docs/.gitignore

**Comment by deemaalomair1** [comment] 2019-10-10 16:16
hello Dr.Smith

sorry for that, but i miss understanding what you mean by blank project template. i thought it is the latex file for SRS. 

I think i added all the files now .. i am not sure if what i have done is right.

thank you

**Comment by smiths** [comment] 2019-10-10 17:08
Thank you @deemaalomair1.  Your new folder structure looks correct to me.

**Comment by smiths** [comment] 2019-10-20 20:21
@deemaalomair1,  you undid the changes that I made to your SRS.tex file.  I had to redo the changes so that it could compile.  The changes are in commit b0be00e.  You should do a git pull before any further edits to the document.  I don't want to fix the document a third time.  :smile:  I also made some other changes, as follows:

- 80 character width for the text in the tex file
- renamed the `.gitignore` file so that it works properly
- removed some unnecessary white space in the tex file
- removed some unnecessary paragraph end characters (`//`)

Going forward, please use an editor that lets you keep the lines to 80 characters width.  Your text editor will likely have a facility for this.

**Comment by caobo1994** [comment] 2019-10-20 20:55
@smiths Sorry to bother you, sir, but it just occurs to me. Is it really necessary to observe the 80-character width rule now? Most modern editors can do word wrap and show line numbers, thus display long lines with multiple short lines, while using line numbers to identify them as the same line.

Furthermore, this rule is easily broken when some words are added to a line, and it turns into an 80-plus or 90 plus line. Simply breaking it will make it two lines with less than 50 characters, and adjusting the whole paragraph is a big and tedious task.

I think it is highly possible that I might be wrong, and there are reasons behind this rule in modern days, but I just cannot help but wondering these reasons. Could you offer me your ideas? Thanks!

**Comment by smiths** [comment] 2019-11-01 23:14
Thank you for your question @caobo1994.  I apologize for the delay in replying.  This issue has come up in almost everyone's tex files, so I'm going to at the others on this repo: @sorainsm, @Ao99, @deemaalomair1, @peter-michalski, @best-zhang-zhi and @sharyuwu.

The main reason for fixed width columns (it doesn't have to be 80 characters, it could be any reasonable width, say 90, 100 or even 120 characters) is for diffs.  When a change is made with very long lines, the entire paragraph is highlighted in the diff.  With separate lines, the diff can pinpoint exactly what change has been made.  

Compare:
https://github.com/caobo1994/FourierSeries/commit/a87d24c7449bf1eec7d49bf691dab6ab519a8426
to
https://github.com/JacquesCarette/Drasil/commit/b1f3d80bef9055ca078c1a456687d0bdd5d2a715

The readability of the diffs is very helpful for quick reviews.  For one developer it doesn't matter too much, but when collaborating, the time saved by reviewers is very helpful.

Also, I'm not asking anyone to create 80 character columns manually.  Modern editors should have a feature to automate this.  With emacs it is called auto filling a paragraph.  For my editor there is a simple key stroke that automatically reformats with hard returns in the right places.  For other editors, you might want to look for changing the behaviour of hard wraps versus soft wraps.  Google should help with this.

I hope this explanation is helpful.  Let me know if you, or anyone else, has any follow-up questions.  If everyone could start doing 80 character columns, it would definitely save me time on the reviews.  :smile:

**Comment by smiths** [comment] 2019-11-01 23:15
I believe the original issue has been dealt with, so I will close this issue.  If anyone has a follow-up question, it can still be posted here.

**Closed as completed by smiths** 2019-11-01 23:15 UTC
